baseURL = 'https://www.linktb.com/'
languageCode = 'zh-cn'
title = 'deepbook2learn'
theme = 'hugo-theme-stack'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
[params]
  math = true